M48
; DRILL file {KiCad 9.0.2} date 2025-11-17T19:56:27+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-17T19:56:27+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.730
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.300
%
G90
G05
T1
X82.85Y-61.35
X90.15Y-57.05
X90.15Y-61.35
T2
X143.8Y-76.8
X155.8Y-76.8
M30
